---
title: "Find LOO results for time-series-trend analysis"
output: html_notebook
---

This notebook is used to extract looic results from time_series_trend_Four_* analysis

```{r}
rm(list=ls())

# tic <- Sys.time()
# Sys <- Sys.info()
source('Dc_Indonesia_nesting_fcns.R')
#library(rjags)

library(jagsUI)
library(coda)
library(tidyverse)
library(loo)

save.data <- T
save.fig <- F
run.date <- "2019-04-12"

year.begin <- 2003
year.end <- 2018

filename.root <- paste0("SSAR1_norm_norm_trend_Four_independentUQs_JM12_W12_",
                        year.begin, "_", year.end, "_", run.date)
```

Bring in the output file

```{r}
results <- readRDS(file = paste0("RData/", filename.root, ".rds"))
jm <- results$jm
jags.data <- results$jm$model$cluster1$data()
MCMC.params <- data.frame(n.chains = jm$mcmc.info$n.chains,
                          n.samples = jm$mcmc.info$n.iter,
                          n.burnin = jm$mcmc.info$n.burnin,
                          n.thin = jm$mcmc.info$n.thin)

n.per.chain <- (MCMC.params$n.samples - MCMC.params$n.burnin)/MCMC.params$n.thin
#   
# reduce the dimension by MCMC iterations by year x month
loglik.JM <- t(apply(jm$sims.list$loglik[,,,1], 
                     MARGIN = 1, 
                     FUN = function(x) as.vector(t(x))))
   
loglik.W <- t(apply(jm$sims.list$loglik[,,,2],
                    MARGIN = 1,
                    FUN = function(x) as.vector(t(x))))

# convert the data (y) into a vector also:
y.JM <- as.vector(t(jags.data$y[,,1]))
y.W <- as.vector(t(jags.data$y[,,2]))
#   
loglik.obs.JM <- loglik.JM[, !is.na(y.JM)]
loglik.obs.W <- loglik.W[, !is.na(y.W)]
#   
#   # get rid of NA columns - even if data existed (for example the first value) - no likelihood
#   # for the first data point - this is not an issue for this case so skip
#   loglik.obs.JM <- loglik.obs.JM[, colSums(is.na(loglik.obs.JM)) == 0]
#   loglik.obs.W <- loglik.obs.W[, colSums(is.na(loglik.obs.W)) == 0]
#   

loglik.obs <- cbind(loglik.obs.JM, loglik.obs.W)
#   # cores = 1 is needed in the relative_eff function if the number of cores was set to more than
#   # 1 with options(mc.cores = parallel::detectCores()) or something similear. See also here:
#   # https://discourse.mc-stan.org/t/error-in-loo-relative-eff-related-to-options-mc-cores/5610/2
#   
Reff <- relative_eff(exp(loglik.obs),
                     chain_id = rep(1:MCMC.params$n.chains,
                                    each = n.per.chain),
                     cores = 1)
#   
loo.out <- loo(loglik.obs, r_eff = Reff, cores = 1)
#   ####
# loo.out <- pareto.k.diag.3D(jm, MCMC.params, jags.data)

```

plot model fit statistics - pareto k
```{r}

pareto.k <- loo.out$diagnostics$pareto_k
data.y <- na.omit(c(y.JM, y.W))
# 
pareto.df <- data.frame(y = data.y,
                        khat = pareto.k,
                        datapoint = seq(from = 1, to = length(data.y)),
                        k0.7 = cut(pareto.k,
                                   breaks = c(0, 0.7, 1.5),
                                   labels = c("<=0.7", ">0.7")))
p.2 <- ggplot(data = pareto.df) +
  geom_path(aes(x = datapoint, y = y), alpha = 0.5) +
  geom_point(aes(x = datapoint, y = y,
                 size = khat,
                 color = k0.7)) +
  scale_size_continuous(limits = c(0.0, 1.3),
                        range = c(1, 4))+
  scale_color_manual(values = c("<=0.7" = "black",
                                ">0.7" = "red"))
p.2
```

```{r}

fill.color <-  "darkseagreen"
fill.color.N1 <- "blue4"
fill.color.N2 <- "gold4"
fill.color.summer <- "darksalmon"
fill.color.winter <- "gray65"
fill.alpha <-  0.65
line.color <-  "darkblue"
line.color.N <- "cadetblue"
line.color.summer <- "red3"
line.color.winter <- "greenyellow"
data.color <- "black"
data.size <- 1.5
obsd.color <- "red2"
maxN <- 10000

Xs.stats <- results$Xs.stats
ys.stats <- results$ys.stats
Ns.stats <- results$Ns.stats
p.1a <- ggplot() +
  geom_ribbon(data = Xs.stats,
              aes(x = time, 
                  ymin = low, 
                  ymax = high),
              fill = fill.color,
              alpha = fill.alpha) + 
  geom_point(data = Xs.stats,
             aes(x = time, 
                 y = median),
             color = data.color,
             alpha = 0.5) +
  geom_line(data = Xs.stats,
            aes(x = time, 
                y = median),
            color = line.color,
            alpha = 0.5) +
  geom_point(data = ys.stats,
             aes(x = time, 
                 y = log(obsY)),
             color = obsd.color,
             alpha = 0.5) + 
  geom_ribbon(data = Ns.stats,
              aes(x = time, 
                  ymin = low,
                  ymax = high),
              color = fill.color.N1,
              alpha = fill.alpha) + 
  geom_line(data = Ns.stats,
            aes(x = time, y = median),
            color = line.color.N,
            alpha = 0.5,
            size = 1.5) + 
  scale_x_continuous(breaks = seq(year.begin, year.end, 5),
                     limits = c(year.begin, year.end)) +
  scale_y_continuous(limits = c(0, log(maxN))) + 
  facet_grid(rows = vars(location)) + 
  labs(x = '', y = 'log(# nests)')  +
  theme(axis.text = element_text(size = 12),
        text = element_text(size = 12))

p.1a

```





